"""Integration tests using fixtures generated by SmokeTests. Run from sample root."""
import os
from pathlib import Path
import tempfile
import unittest
from zipfile import ZipFile

from document_sdk import load_service

# Use evaluation mode and synthetic fixtures; temporary outputs leave originals intact.
SDK = load_service(allow_trial=True)
FIXTURES = Path(os.environ["TEST_FIXTURES"]).resolve()


class BridgeTests(unittest.TestCase):
    def test_all_seven_operations_from_python(self):
        """Verify all seven operations create readable document containers or PDF files."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            # Process each Office format, checking its ZIP structure and resulting PDF.
            for ext, mark, convert, pdf_name in [
                ("docx", SDK.MarkWord, SDK.WordToPdf, "word"),
                ("xlsx", SDK.MarkExcel, SDK.ExcelToPdf, "excel"),
                ("pptx", SDK.MarkPowerPoint, SDK.PowerPointToPdf, "powerpoint"),
            ]:
                output = root / ("marked." + ext)
                mark(str(FIXTURES / ("input." + ext)), str(output), "PYTHON-CONFIDENTIAL")
                # Office documents are ZIP containers; confirm integrity and label text.
                with ZipFile(output) as archive:
                    self.assertIsNone(archive.testzip())
                    self.assertTrue(any(b"PYTHON-CONFIDENTIAL" in archive.read(name)
                                        for name in archive.namelist() if name.endswith(".xml")))
                pdf = root / (pdf_name + ".pdf")
                convert(str(output), str(pdf))
                self.assertTrue(pdf.read_bytes().startswith(b"%PDF-"))
            # Confirm watermarking creates a different PDF from the source.
            SDK.WatermarkPdf(str(root / "powerpoint.pdf"), str(root / "watermarked.pdf"), "PYTHON-RESTRICTED")
            watermarked = (root / "watermarked.pdf").read_bytes()
            self.assertTrue(watermarked.startswith(b"%PDF-"))
            self.assertNotEqual(watermarked, (root / "powerpoint.pdf").read_bytes())

    def test_paths_and_labels_are_passed_as_data(self):
        """Verify spaces and shell characters are handled as data, not shell commands."""
        with tempfile.TemporaryDirectory(prefix="SDK spaces ") as tmp:
            output = Path(tmp) / "marked ; $file.docx"
            SDK.MarkWord(str(FIXTURES / "input.docx"), str(output), 'R&D "INTERNAL"; $HOME')
            self.assertTrue(output.is_file())
            with ZipFile(output) as archive:
                self.assertIsNone(archive.testzip())

    def test_existing_output_is_overwritten(self):
        """Confirm the current overwrite policy replaces an existing file with a DOCX."""
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "existing.docx"
            output.write_bytes(b"Old output")
            SDK.MarkWord(str(FIXTURES / "input.docx"), str(output), "CONFIDENTIAL")
            with ZipFile(output) as archive:
                self.assertIsNone(archive.testzip())

    def test_invalid_label_fails_without_creating_output(self):
        """Confirm invalid labels report an error before writing an output file."""
        with tempfile.TemporaryDirectory() as tmp:
            output = Path(tmp) / "invalid.docx"
            with self.assertRaises(RuntimeError):
                SDK.MarkWord(str(FIXTURES / "input.docx"), str(output), "bad\nlabel")
            self.assertFalse(output.exists())

    def test_word_reclassification_replaces_owned_label(self):
        """Confirm reclassification replaces the earlier sample-owned Word label."""
        with tempfile.TemporaryDirectory() as tmp:
            first = Path(tmp) / "first.docx"
            second = Path(tmp) / "second.docx"
            SDK.MarkWord(str(FIXTURES / "input.docx"), str(first), "OLD-CLASSIFICATION")
            SDK.MarkWord(str(first), str(second), "NEW-CLASSIFICATION")
            with ZipFile(second) as archive:
                xml = b"".join(archive.read(n) for n in archive.namelist() if n.endswith(".xml"))
            self.assertIn(b"NEW-CLASSIFICATION", xml)
            self.assertNotIn(b"OLD-CLASSIFICATION", xml)


# Run this test suite when the file is executed directly.
if __name__ == "__main__":
    unittest.main()
